
ASTYLE=astyle
ASTYLE_ARG=--mode=c --style=allman --indent=spaces=2 --align-pointer=name --align-reference=name \
	--min-conditional-indent=0 --max-code-length=100

astyle:
	${ASTYLE} ${ASTYLE_ARG} ../src/amelethdf/*.h ../src/amelethdf/*.c ../src/test/*.h ../src/test/*.c 
